server:
  port: 3002
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

weather:
  api:
    host: <api-host>
    api-key: <api-key>
spring:
  application:
    name: mcp-server-custom
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://<ip>:<port>/<database_name>?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>
    hikari:
      connection-timeout: 30000
      idle-timeout: 25000
      max-lifetime: 30000
      validation-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  main:
    banner-mode: off
#    web-application-type: none

logging:
#  pattern:
#    console:
  file:
    name: ./logs/info.log
